/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

/**
 *
 * @author Eduard
 */
public class GameWindowFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameWindowFrame
     */
    public GameWindowFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowContentPanel = new javax.swing.JPanel();
        menuPanel = new game.MenuPanel();
        gameOverPanel = new game.GameOverPanel();
        registerPanel = new game.RegisterPanel();
        loginPanel = new game.LoginPanel();
        gameplayPanel = new game.GameplayPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        windowContentPanel.setLayout(new java.awt.CardLayout());

        menuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPanelMouseClicked(evt);
            }
        });
        windowContentPanel.add(menuPanel, "menuCard");
        menuPanel.getAccessibleContext().setAccessibleName("menuPanel");

        windowContentPanel.add(gameOverPanel, "gameOverCard");
        gameOverPanel.getAccessibleContext().setAccessibleName("gameOverPanel");

        windowContentPanel.add(registerPanel, "registerCard");
        registerPanel.getAccessibleContext().setAccessibleName("registerPanel");

        windowContentPanel.add(loginPanel, "loginCard");
        windowContentPanel.add(gameplayPanel, "gameplayCard");
        gameplayPanel.getAccessibleContext().setAccessibleName("gameplayPanel");

        getContentPane().add(windowContentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuPanelMouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private game.GameOverPanel gameOverPanel;
    private game.GameplayPanel gameplayPanel;
    private game.LoginPanel loginPanel;
    private game.MenuPanel menuPanel;
    private game.RegisterPanel registerPanel;
    private javax.swing.JPanel windowContentPanel;
    // End of variables declaration//GEN-END:variables
}
