/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import com.mysql.jdbc.Connection;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Eduard
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        usernameLabel.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        add(usernameLabel, gridBagConstraints);

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 1);
        add(usernameTextField, gridBagConstraints);

        passwordLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        add(passwordLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        add(passwordTextField, gridBagConstraints);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        add(loginButton, gridBagConstraints);

        getAccessibleContext().setAccessibleName("loginPanel");
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:'
        String uname = usernameTextField.getText();
        String pwd = passwordTextField.getText();
        Game gameInstance = Game.getInstance();
        boolean hasAccount = false;
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Class not found " + e);
        }

        System.out.println("JDBC Class found");
        String query = "select * from users where username = ? and password = ?";
        ResultSet rs = null;
        PreparedStatement ps = null;
        try (Connection con = (Connection) DriverManager.getConnection(
            "jdbc:mysql://localhost/tictactoedb", "admin", "superduperpwd")) {
            ps = con.prepareStatement(query);

            ps.setString(1, uname);
            ps.setString(2, pwd);

            rs = ps.executeQuery();

            if (rs.next()) {
                // has account log the user in
                gameInstance.logUserIn();
                JPanel parentPanel = (JPanel) this.getParent();
                CardLayout cl = (CardLayout) parentPanel.getLayout();
                cl.show(parentPanel, "menuCard");
                // change username in menu panel
                Component[] containers = parentPanel.getComponents();
                for(Component comp : containers){
                    JPanel cPanel = (JPanel) comp;
                    System.out.println(cPanel.getAccessibleContext().getAccessibleName());

                    if(cPanel.getAccessibleContext().getAccessibleName().equals("menuPanel")) {
                        // found it, now change textfield
                        Component[] loginPanelComponents = cPanel.getComponents();
                        for(Component menuComponent: loginPanelComponents){
                            if(menuComponent instanceof JLabel && ((JLabel)menuComponent).getAccessibleContext().getAccessibleName().equals("usernameLabel")){
                                ((JLabel)menuComponent).setText("User: " + uname);
                            }
                        }
                        
                        break;
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            
            try {
                if(rs != null)
                    rs.close();
                if(ps != null)
                    ps.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
