/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eduard.tictactoedesktopclient.game.ui;

import com.eduard.tictactoedesktopclient.game.GameController;

/**
 *
 * @author Eduard
 */
public class DrawPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        drawPanelContent = new javax.swing.JPanel();
        drawImage = new javax.swing.JLabel();
        drawText = new javax.swing.JLabel();
        restartGamePanel = new javax.swing.JPanel();
        restartGameButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        drawPanelContent.setLayout(new java.awt.GridBagLayout());

        drawImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawGame.png"))); // NOI18N
        drawPanelContent.add(drawImage, new java.awt.GridBagConstraints());

        drawText.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 24)); // NOI18N
        drawText.setForeground(new java.awt.Color(71, 71, 71));
        drawText.setText("Draw! Try again !");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        drawPanelContent.add(drawText, gridBagConstraints);

        add(drawPanelContent);

        restartGamePanel.setLayout(new java.awt.GridBagLayout());

        restartGameButton.setBackground(new java.awt.Color(255, 255, 255));
        restartGameButton.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 24)); // NOI18N
        restartGameButton.setForeground(new java.awt.Color(71, 71, 71));
        restartGameButton.setText("Restart");
        restartGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartGameButtonActionPerformed(evt);
            }
        });
        restartGamePanel.add(restartGameButton, new java.awt.GridBagConstraints());

        add(restartGamePanel);
    }// </editor-fold>//GEN-END:initComponents

    private void restartGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartGameButtonActionPerformed
        GameController gameInstance = GameController.getInstance();
        gameInstance.restartGame();

    }//GEN-LAST:event_restartGameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel drawImage;
    private javax.swing.JPanel drawPanelContent;
    private javax.swing.JLabel drawText;
    private javax.swing.JButton restartGameButton;
    private javax.swing.JPanel restartGamePanel;
    // End of variables declaration//GEN-END:variables
}
