/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eduard.tictactoedesktopclient.game.ui;

import java.awt.CardLayout;

/**
 *
 * @author Eduard
 */
public class GameWindowFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameWindowFrame
     */
    public GameWindowFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowContentPanel = new javax.swing.JPanel();
        menuPanel = new com.eduard.tictactoedesktopclient.game.ui.MenuPanel();
        loginPanel = new com.eduard.tictactoedesktopclient.game.ui.LoginPanel();
        registerPanel = new com.eduard.tictactoedesktopclient.game.ui.RegisterPanel();
        gameOverPanel = new com.eduard.tictactoedesktopclient.game.ui.GameOverPanel();
        gameplayPanel = new com.eduard.tictactoedesktopclient.game.ui.GameplayPanel();
        loadingScreenPanel = new com.eduard.tictactoedesktopclient.game.ui.LoadingScreenPanel();
        victoryPanel = new com.eduard.tictactoedesktopclient.game.ui.VictoryPanel();
        drawPanel = new com.eduard.tictactoedesktopclient.game.ui.DrawPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super TicTacToe");
        setMinimumSize(new java.awt.Dimension(500, 500));

        windowContentPanel.setName("Super TicTacToe "); // NOI18N
        windowContentPanel.setLayout(new java.awt.CardLayout());
        windowContentPanel.add(menuPanel, "menuCard");
        menuPanel.getAccessibleContext().setAccessibleName("");

        windowContentPanel.add(loginPanel, "loginCard");
        windowContentPanel.add(registerPanel, "registerCard");
        registerPanel.getAccessibleContext().setAccessibleName("registerPanel");

        windowContentPanel.add(gameOverPanel, "gameOverCard");
        gameOverPanel.getAccessibleContext().setAccessibleName("gameOverPanel");

        windowContentPanel.add(gameplayPanel, "gameplayCard");
        gameplayPanel.getAccessibleContext().setAccessibleName("gameplayPanel");

        windowContentPanel.add(loadingScreenPanel, "loadingCard");
        windowContentPanel.add(victoryPanel, "victoryCard");
        windowContentPanel.add(drawPanel, "drawCard");
        drawPanel.getAccessibleContext().setAccessibleName("drawPanel");

        getContentPane().add(windowContentPanel, java.awt.BorderLayout.CENTER);
        windowContentPanel.getAccessibleContext().setAccessibleName("windowContentPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuPanelMouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.eduard.tictactoedesktopclient.game.ui.DrawPanel drawPanel;
    private com.eduard.tictactoedesktopclient.game.ui.GameOverPanel gameOverPanel;
    private com.eduard.tictactoedesktopclient.game.ui.GameplayPanel gameplayPanel;
    private com.eduard.tictactoedesktopclient.game.ui.LoadingScreenPanel loadingScreenPanel;
    private com.eduard.tictactoedesktopclient.game.ui.LoginPanel loginPanel;
    private com.eduard.tictactoedesktopclient.game.ui.MenuPanel menuPanel;
    private com.eduard.tictactoedesktopclient.game.ui.RegisterPanel registerPanel;
    private com.eduard.tictactoedesktopclient.game.ui.VictoryPanel victoryPanel;
    private javax.swing.JPanel windowContentPanel;
    // End of variables declaration//GEN-END:variables
}
