/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eduard.tictactoedesktopclient.game.ui;

/**
 *
 * @author Eduard
 */
public class LoadingScreenPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoadingScreenPanel
     */
    public LoadingScreenPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gifLabel = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        gifLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gifLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loadingGif.gif"))); // NOI18N
        add(gifLabel, "loadingCard");

        getAccessibleContext().setAccessibleName("loadingPanel");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gifLabel;
    // End of variables declaration//GEN-END:variables
}
