/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eduard.tictactoedesktopclient.game.ui;

import com.eduard.tictactoedesktopclient.game.GameController;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.UnsupportedEncodingException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Eduard
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        backButtonPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        loginFormPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(71, 71, 71));
        backButton.setText("Back");
        backButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backButtonPanelLayout = new javax.swing.GroupLayout(backButtonPanel);
        backButtonPanel.setLayout(backButtonPanelLayout);
        backButtonPanelLayout.setHorizontalGroup(
            backButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        backButtonPanelLayout.setVerticalGroup(
            backButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backButtonPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(backButton))
        );

        backButton.getAccessibleContext().setAccessibleName("backButton");

        add(backButtonPanel);
        backButtonPanel.getAccessibleContext().setAccessibleName("backButtonPanel");

        loginFormPanel.setLayout(new java.awt.GridBagLayout());

        usernameLabel.setFont(new java.awt.Font("Proxima Nova Lt", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(71, 71, 71));
        usernameLabel.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        loginFormPanel.add(usernameLabel, gridBagConstraints);

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 1);
        loginFormPanel.add(usernameTextField, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Proxima Nova Lt", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(71, 71, 71));
        passwordLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        loginFormPanel.add(passwordLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        loginFormPanel.add(passwordTextField, gridBagConstraints);

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(71, 71, 71));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        loginFormPanel.add(loginButton, gridBagConstraints);

        messageLabel.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        loginFormPanel.add(messageLabel, gridBagConstraints);
        messageLabel.getAccessibleContext().setAccessibleName("messageLabel");

        add(loginFormPanel);

        getAccessibleContext().setAccessibleName("loginPanel");
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:'
        String uname = usernameTextField.getText();
        String pwd = passwordTextField.getText();
        GameController gameInstance = GameController.getInstance();
        boolean hasAccount = false;
        URL servletURL;
        String urlParameters;
        try {
            urlParameters = "username="+URLEncoder.encode(uname, "UTF-8") + "&password=" + URLEncoder.encode(pwd,"UTF-8");
            servletURL = new URL("http://localhost:9999/TicTacToeWeb/Login?"+urlParameters);
            HttpURLConnection servletConnection = (HttpURLConnection) servletURL.openConnection();
            servletConnection.setRequestMethod("POST");
           
            Map<String,List<String>> headerFields = servletConnection.getHeaderFields();
            Set<String> headerFieldsSet = headerFields.keySet();
            Iterator<String> headerFieldsIter = headerFieldsSet.iterator();
            while(headerFieldsIter.hasNext()){
                String headerFieldKey = headerFieldsIter.next();
                if("Set-Cookie".equalsIgnoreCase(headerFieldKey)){
                    List<String> headerFieldValue = headerFields.get(headerFieldKey);
                    headerFieldValue.forEach((String s) -> {
                        String[] parts = s.split("=");
                        if (parts[0].equals("loginStatus")) {
                            if (parts[1].substring(0, 6).equals("logged")) {
                                GameController gameInstance1 = GameController.getInstance();
                                gameInstance1.logUserIn();
                                gameInstance1.switchToCard("menuCard");
                                gameInstance1.setMyUsername(uname);
                                GameController.setLabel("messageLabel", "You logged in.", gameInstance1.getRootContainer());
                                GameController.setLabel("usernameLabel", "Username: " + uname, gameInstance1.getRootContainer());
                                
                            } else {
                                GameController.setLabel("messageLabel", "Username or password incorect.", gameInstance.getRootContainer());
                            }
                        }
                    });
                }
            }
           
        } catch (MalformedURLException ex ) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        /*try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Class not found " + e);
        }

        System.out.println("JDBC Class found");
        String query = "select * from users where username = ? and password = ?";
        ResultSet rs = null;
        PreparedStatement ps = null;
        try (Connection con = (Connection) DriverManager.getConnection(
            "jdbc:mysql://localhost/tictactoedb", "admin", "superduperpwd")) {
            ps = con.prepareStatement(query);

            ps.setString(1, uname);
            ps.setString(2, pwd);

            rs = ps.executeQuery();

            if (rs.next()) {
                // has account log the user in
                gameInstance.logUserIn();
                gameInstance.setMyUsername(uname);
                gameInstance.switchToCard("menuCard");
                // change username in menu panel
                GameController.setLabel("usernameLabel","Username: " + uname, gameInstance.getRootContainer());
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            
            try {
                if(rs != null)
                    rs.close();
                if(ps != null)
                    ps.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        GameController gameInstance = GameController.getInstance();
        gameInstance.switchToCard("menuCard");
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel backButtonPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginFormPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
