/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eduard.tictactoedesktopclient.game.ui;

import com.eduard.tictactoedesktopclient.game.GameController;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Eduard
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        backButtonPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        registerFormPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        messagePanel = new javax.swing.JPanel();
        firstNameErrorLabel = new javax.swing.JLabel();
        lastNameErrorLabel = new javax.swing.JLabel();
        emailErrorLabel = new javax.swing.JLabel();
        usernameErrorLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 245));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(71, 71, 71));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backButtonPanelLayout = new javax.swing.GroupLayout(backButtonPanel);
        backButtonPanel.setLayout(backButtonPanelLayout);
        backButtonPanelLayout.setHorizontalGroup(
            backButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(553, Short.MAX_VALUE))
        );
        backButtonPanelLayout.setVerticalGroup(
            backButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        add(backButtonPanel);

        registerFormPanel.setLayout(new java.awt.GridBagLayout());

        firstNameLabel.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 0, 14)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(71, 71, 71));
        firstNameLabel.setText("First name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        registerFormPanel.add(firstNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        registerFormPanel.add(firstNameTextField, gridBagConstraints);

        lastNameLabel.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 0, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(71, 71, 71));
        lastNameLabel.setText("Last name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        registerFormPanel.add(lastNameLabel, gridBagConstraints);

        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        registerFormPanel.add(lastNameTextField, gridBagConstraints);

        emailLabel.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(71, 71, 71));
        emailLabel.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        registerFormPanel.add(emailLabel, gridBagConstraints);

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        registerFormPanel.add(emailTextField, gridBagConstraints);

        usernameLabel.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(71, 71, 71));
        usernameLabel.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        registerFormPanel.add(usernameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        registerFormPanel.add(usernameTextField, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(71, 71, 71));
        passwordLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        registerFormPanel.add(passwordLabel, gridBagConstraints);

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        registerFormPanel.add(passwordTextField, gridBagConstraints);

        registerButton.setBackground(new java.awt.Color(255, 255, 255));
        registerButton.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 14)); // NOI18N
        registerButton.setForeground(new java.awt.Color(71, 71, 71));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 0);
        registerFormPanel.add(registerButton, gridBagConstraints);

        add(registerFormPanel);

        firstNameErrorLabel.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 14)); // NOI18N
        firstNameErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        lastNameErrorLabel.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 14)); // NOI18N
        lastNameErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        emailErrorLabel.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 14)); // NOI18N
        emailErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        usernameErrorLabel.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 14)); // NOI18N
        usernameErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        messageLabel.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 14)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
            .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(messagePanelLayout.createSequentialGroup()
                    .addGap(0, 313, Short.MAX_VALUE)
                    .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(firstNameErrorLabel)
                        .addComponent(lastNameErrorLabel)
                        .addComponent(emailErrorLabel)
                        .addComponent(usernameErrorLabel)
                        .addComponent(messageLabel))
                    .addGap(0, 313, Short.MAX_VALUE)))
        );
        messagePanelLayout.setVerticalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
            .addGroup(messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(messagePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(firstNameErrorLabel)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lastNameErrorLabel)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(emailErrorLabel)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(usernameErrorLabel)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(messageLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        firstNameErrorLabel.getAccessibleContext().setAccessibleName("firstNameErrorLabel");
        lastNameErrorLabel.getAccessibleContext().setAccessibleName("lastNameErrorLabel");
        emailErrorLabel.getAccessibleContext().setAccessibleName("emailErrorLabel");
        usernameErrorLabel.getAccessibleContext().setAccessibleName("usernameErrorLabel");
        messageLabel.getAccessibleContext().setAccessibleName("messageLabel");

        add(messagePanel);
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        GameController gameInstance = GameController.getInstance();
        URL servletURL;
        try {
            String urlParameters = "first_name="+URLEncoder.encode(firstNameTextField.getText(), "UTF-8")
                            + "&last_name=" + URLEncoder.encode(lastNameTextField.getText(),"UTF-8") 
                            + "&email=" + URLEncoder.encode(emailTextField.getText(),"UTF-8")
                            + "&username=" + URLEncoder.encode(usernameTextField.getText(), "UTF-8")
                            + "&password=" + URLEncoder.encode(passwordTextField.getText(),"UTF-8");
                    
            servletURL = new URL("http://localhost:9999/TicTacToeWeb/Register?"+urlParameters);
            HttpURLConnection servletConnection = (HttpURLConnection) servletURL.openConnection();
            servletConnection.setRequestMethod("POST");
           
            Map<String,List<String>> headerFields = servletConnection.getHeaderFields();
            Set<String> headerFieldsSet = headerFields.keySet();
            Iterator<String> headerFieldsIter = headerFieldsSet.iterator();
            
            while(headerFieldsIter.hasNext()){
                String headerFieldKey = headerFieldsIter.next();
                
                if("Set-Cookie".equalsIgnoreCase(headerFieldKey)){
                    List<String> headerFieldValue = headerFields.get(headerFieldKey);
                    headerFieldValue.forEach((String s) -> {
                        System.out.println(s);
                        String[] parts = s.split("=");
                        if(parts[0].equals("registerStatus")) {
                            
                            if(parts[1].substring(0, 2).equals("ok")){
                                gameInstance.switchToCard("menuCard");
                                GameController.setLabel("messageLabel", "You successfully registered.", gameInstance.getRootContainer());
                            }
                        }
                        if(parts[0].equals("registerErrors")){
                            int limit = parts[1].indexOf(";");
                            String info = parts[1].substring(0, limit);
                            String[] errors = info.split("[\\|]");
                            for(String e : errors){
                                switch(e){
                                    case "fname":
                                        firstNameErrorLabel.setText("First name not valid.");
                                        break;
                                    case "lname":
                                        lastNameErrorLabel.setText("Last name not valid.");
                                        break;
                                    case "email":
                                        emailErrorLabel.setText("Email not valid.");
                                        break;
                                    case "user":
                                        usernameErrorLabel.setText("Username already taken.");
                                        break;
                                }
                            }
                            
                        }
                        
                    });
                }
            }
           
        } catch (MalformedURLException ex ) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        GameController gameInstance = GameController.getInstance();
        gameInstance.switchToCard("menuCard");
    }//GEN-LAST:event_backButtonActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel backButtonPanel;
    private javax.swing.JLabel emailErrorLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameErrorLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel lastNameErrorLabel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerFormPanel;
    private javax.swing.JLabel usernameErrorLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
