/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eduard.tictactoedesktopclient.game.ui;

import com.eduard.tictactoedesktopclient.game.GameController;

/**
 *
 * @author Eduard
 */
public class VictoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form VictoryPanel
     */
    public VictoryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        victoryImagePanel = new javax.swing.JPanel();
        victoryCupImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        restartGamePanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        victoryImagePanel.setLayout(new java.awt.GridBagLayout());

        victoryCupImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goldenCup.png"))); // NOI18N
        victoryCupImage.setPreferredSize(new java.awt.Dimension(300, 298));
        victoryImagePanel.add(victoryCupImage, new java.awt.GridBagConstraints());

        jLabel1.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 71, 71));
        jLabel1.setText("Congratulations! You won!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        victoryImagePanel.add(jLabel1, gridBagConstraints);

        add(victoryImagePanel);

        restartGamePanel.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Proxima Nova Alt Cn Lt", 1, 24)); // NOI18N
        jButton1.setText("Restart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        restartGamePanel.add(jButton1, new java.awt.GridBagConstraints());

        add(restartGamePanel);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GameController gameInstance = GameController.getInstance();
        gameInstance.restartGame();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel restartGamePanel;
    private javax.swing.JLabel victoryCupImage;
    private javax.swing.JPanel victoryImagePanel;
    // End of variables declaration//GEN-END:variables
}
